export type ProcessStatus = 'deployed' | 'undeployed' | 'suspended';

export interface ProcessDefinition {
    id: string; // The unique ID typically generated by the database or UUID
    key: string; // The process key from BPMN XML (e.g., id of bpmn:Process)
    name: string; // The process name from BPMN XML (e.g., name of bpmn:Process)
    version: number;
    status: ProcessStatus;
    xmlContent: string;
    fileName?: string;
    deployTime?: string;
    creator: string;
    createTime: string;
}
